### ISSUE TITLE
version mismatched between crates.io and github src

### ISSUE THREAD

**Issue by tjyang** [RustRPM/cargo-rpm#15]
Hi 

On github here, the version is only to version 0.1.1, but the on crates.io the version is 0,2.0.
Pls sync the github src.

**Comment by tarcieri** [comment]
Wow, good point. I have no idea what happened there but I have no local commit or tag for the v0.2.0 release. Very strange.

I will attempt to reconcile what's in the current v0.2.0 crate release vs what's in GitHub. Seems some history didn't get pushed, and my local copies on all devices I'd think I would've worked on this on match GitHub.

**Comment by tarcieri** [comment]
Okay, I have tried my best to resolve this. In the future I will do releases via PRs, like this:

https://github.com/RustRPM/cargo-rpm/pull/21
