### ISSUE TITLE
[RFE] Switching over to clap for cmd arg processing

### ISSUE THREAD

**Issue by tjyang** [RustRPM/cargo-rpm#16]
I am learning rust and I use clap for a few exercises rs code. 
Any interests to switch over to clap crate ?

**Comment by tarcieri** [comment]
I’ve wanted to move this crate over to Abscissa:

https://github.com/iqlusioninc/abscissa/

It uses gumdrop as an option parser. It has significantly fewer dependencies than clap, and was built from the groud up to use proc macros, as opposed to structopt which was added as an afterthought.

**Comment by tjyang** [comment]
Thanks for sharing the roadmap info. I may learn abscissa mirco framework.

**Comment by tjyang** [comment]
Looks like "cargo" itself is is using clap for arg processing also ;).  This make me( a rust beginner) feel clap is a better choice.
 
Won't using non-clap crate make it harder for cargo-rpm be part of standard cargo sub-command ?

**Comment by tarcieri** [comment]
cargo subcommands are independent executables. It doesn't really matter what cargo is using.

I'm aware clap is quite popular. I used it quite a bit a few years ago. However it was never designed to use proc macros, and also I find structopt to be pretty gross compared to gumdrop. Projects to improve clap's proc macros have stalled. I'm not really happy about clap's current state.

**Comment by tjyang** [comment]
Thanks for the detail response.  
I had to read the [init.rs src code](https://github.com/learnrust/cargo-rpm/blob/master/src/init.rs#L20) to understand how to feed extra arg after "cargo rpm init ARGS".
Here is [my note to myself](https://github.com/learnrust/cargo-rpm/commit/51f3c3a9d223a1ebb5721fde95a005fd284460ee). 
It is quite tempting for a rust beginner like me to have this improved by clap easily ;)

**Comment by liamdawson** [comment]
@tarcieri do you think that opinion will change with Clap v3?

**Comment by tarcieri** [comment]
@liamdawson I don't think so. The reasons I like `gumdrop`:

- No dependencies
- Custom derive as the one true "DSL" for option parsing
- Comparatively simple

`clap`, even with a hypothetical v3, seems to be continuing to move in the opposite direction from this approach.

All that said, I've been doing some work on Abscissa lately, which I think brings some real benefits over just `clap` alone as an actual command-line application framework:

https://github.com/iqlusioninc/abscissa

While I think `clap` provides great UX, the design choices litter it with incidental complexity.

Where there are UX gaps, especially if I do move everything over to Abscissa, I'd be very interested in addressing them.

**Comment by tarcieri** [comment]
Now that we've migrated to Abscissa, I'd consider this addressed.

clap/structopt v3 looks potentially interesting, but if I do migrate to them, it will be in Abscissa itself.
