### ISSUE TITLE
[RFE] Support building library

### ISSUE THREAD

**Issue by tjyang** [RustRPM/cargo-rpm#17]
Hi 

* I was able to build a rpm with rust binary but not library. Please see logs below.
```
[pi@centos7 sudo_pair]$ git remote -v
origin  git@github.com:learnrust/sudo_pair.git (fetch)
origin  git@github.com:learnrust/sudo_pair.git (push)
[pi@centos7 sudo_pair]$ cargo rpm  init
error: detected unsupported crate type: library (-f to override)
[pi@centos7 sudo_pair]$ cat Cargo.toml
[package]
name    = "sudo_pair"
version = "0.11.1"
license = "Apache-2.0"
edition = "2018"

authors     = ["Stephen Touset <stephen@squareup.com>"]
description = "sudo IO-plugin to require a live human pair"

homepage   = "https://github.com/square/sudo_pair"
repository = "https://github.com/square/sudo_pair.git"
readme     = "../README.md"

categories = [ "command-line-utilities" ]
keywords   = [ "sudo", "sudo-plugin", "dual-control", "sox" ]

[lib]
name       = "sudo_pair"
crate-type = ["cdylib"]

[dependencies]
libc        = '0'
failure     = '0'
sudo_plugin = { version = "1.1", path = "../sudo_plugin" }

[badges]
travis-ci = { repository = "square/sudo_pair" }
[pi@centos7 sudo_pair]$


```

**Comment by tarcieri** [comment]
Yeah, right now cargo-rpm only supports building crates for apps/CLI utilities, not libraries.

For libraries I think we might consider an integration with [rust2rpm](https://pagure.io/fedora-rust/rust2rpm)

**Comment by omac777** [comment]
Yeah, I just discovered this missing feature also when attempting to rpm package quiche 
https://github.com/cloudflare/quiche

```
davidm@io02fedora30 2019-09-11_13:25:45_EDT : ~/Downloads/quiche
 $ cargo rpm init
error: detected unsupported crate type: library (-f to override)
```

I'm attempting to build the latest http3/parallelized curl(https://github.com/curl/curl) with quiche on fedora rawhide.  Here are the steps:

```
git clone https://boringssl.googlesource.com/boringssl
cd boringssl/
emacs CMakeLists.txt &
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
mkdir build
cd build/
cmake ..
make

cargo install cargo-rpm

git clone https://github.com/cloudflare/quiche
cd quiche/
QUICHE_BSSL_PATH="/home/davidm/Downloads/boringssl" cargo build --release
cargo rpm init
cargo rpm build

git clone https://github.com/curl/curl
cd curl/
./buildconf 
./configure --with-quiche=/home/davidm/Downloads/quiche
```

**Comment by tarcieri** [comment]
For now I'd suggest looking at [`rust2rpm`](https://pagure.io/fedora-rust/rust2rpm), which I believe should have this functionality. Going forward for solving this problem for `cargo-rpm`, I think it'd be best to look into if we can consume `rust2rpm` as a library, or failing that, align with the approach it's using to ensure the two tools use compatible methods.

cc @ignatenkobrain

**Comment by igor-raits** [comment]
I would like to see these 2 projects merged :)

**Comment by tarcieri** [comment]
Here are the packaging guidelines for Rust projects:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/

@ignatenkobrain do you think it would be possible for `cargo-rpm` to consume `rust2rpm` as a library and use its spec file generator?

**Comment by igor-raits** [comment]
Can we rather incorporate this codebase into rust2rpm? I'm willing to give you commit rights if you come up with proposal.

But definitely it is more or less usable as a library (probably some things needs to be adjusted, I'm open for PRs).

**Comment by tarcieri** [comment]
@ignatenkobrain it feels like `rust2rpm` has a different workflow? This tool in particular uses a cargo-driven workflow that wraps rpmbuild and otherwise keeps it out of your way. It also supports self-contained RPMs, where `rust2rpm` packages each crate as an RPM.

I’d be happy to also “give up” on the library use case for `cargo rpm`. Our main use case for `cargo rpm` is packaging internal tools in an internal repo with no desire to submit them to official repos. In that case I think it’s somewhat desirable to have self-contained RPMs with minimum external dependencies.

**Comment by igor-raits** [comment]
I would not mind if rust2rpm would get functionality to bundle all dependencies as additional tarball in spec.

**Comment by tarcieri** [comment]
That’d be a start. Perhaps we could find a way to roll the `cargo-rpm` binary into `rust2rpm` as an alternative way of driving the build.

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
