### ISSUE TITLE
Cryptic error message if not in crate root

### ISSUE THREAD

**Issue by liamdawson** [RustRPM/cargo-rpm#27]
If I cd into the `src` folder in my Rust crate and run `cargo rpm build`, I get the following error:

```
error: No such file or directory (os error 2)
```

I would expect a clearer message about why it couldn't build the RPM.

**Comment by tarcieri** [comment]
Yeah, that's a bad error message. A similar limitation in `rustfmt` annoyed me for awhile until you could work around it with `-a`.

I'll try to take a look at doing some general housekeeping work on `cargo-rpm` soon and see if I can address this in the process.

**Comment by lberezy** [comment]
I get this issue too, except I am working with a cargo workspace and I'm in one of the sub crates (the one I have configured with `cargo-rpm` and which builds the binary).

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
