### ISSUE TITLE
Build with different bin dir throws errors

### ISSUE THREAD

**Issue by cholcombe973** [RustRPM/cargo-rpm#35]
So I encountered an error message when trying to install a binary in a directory other than `/usr/bin/` or `/usr/sbin/`.  I tried creating this package metadata in the `Cargo.toml`

```
[package.metadata.rpm.targets]
foo = { path = "/usr/bin/foo" }
bar = { path = "/etc/foo/bar" }
```

I think this line of code is to blame:
https://github.com/RustRPM/cargo-rpm/blob/a92ab8ce23575384fee4e5f4b8857681fa8d3bec/src/commands/init.rs#L139

I think it would be great to be able to specify other paths for installing binaries.

**Comment by tarcieri** [comment]
Sounds like a good suggestion

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
