### ISSUE TITLE
Don't bury the result so deep

### ISSUE THREAD

**Issue by David-OConnor** [RustRPM/cargo-rpm#36]
It would be easier to use if the `rpm` file was placed in `target/rpm`, instead of `/target/release/rpmbuild/RPMs/{architecture}`. It would also be consistent with `cargo wix` and `cargo deb`.

**Comment by tarcieri** [comment]
Good suggestion. Yeah the location is a bit annoying now, it could be moved to `target/rpm` as you suggest

**Comment by anupdhml** [comment]
There's a PR now that should make this easier to deal with: https://github.com/iqlusioninc/cargo-rpm/pull/71

Does not change the output path by default (since that would break existing behavior that someone may be relying on) but users can now override it with a `--output` flag at rpm build time.

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
