### ISSUE TITLE
io error when debug directory but not release directory exists

### ISSUE THREAD

**Issue by yaahc** [RustRPM/cargo-rpm#37]
# The Problem

When you run `cargo clean && cargo rpm build` everything works fine, but if you run `cargo clean && cargo build && cargo rpm build` the rpm build will fail because of an unexpected missing directory.

It looks like this may be a duplicate of https://github.com/RustRPM/cargo-rpm/issues/33 so if this already fixed and just hasn't been released yet then feel free to close this.

**Comment by chewi** [comment]
Yeah I think it's the same. Very confusing! It doesn't appear to have been fixed.

**Comment by chewi** [comment]
I now see it's fixed in master so a new release is needed.

**Comment by tarcieri** [comment]
v0.7.0 has been released
