### ISSUE TITLE
Add documentation about `[package.metadata.rpm]` to the README

### ISSUE THREAD

**Issue by yaahc** [RustRPM/cargo-rpm#38]
I wasn't able to figure out about the existence of this extra toml metadata until I talked to the maintainer and then checked the source code itself to get more specifics.

It would be helpful to include additional documentation that does the following

* Mentions that `cargo rpm init` adds some basic `[package.metadata.rpm]` fields to your Cargo.toml
* Show examples of a Cargo.toml config that include using the `[package.metadata.rpm.files]` field at a minimum
* Bonus points for comprehensively documenting the config format and all available options.

A comprehensive document isn't necessary for the README, all I really needed was knowledge of it's existence and possibly a code sample that showed something like this and mentioned that it takes files from the `.rpm` directory.

```toml
[package.metadata.rpm.files]
"scripts/automation-webhooks.cron" = { path = "/etc/cron.d/automation-webhooks" }
"scripts/automation-webhooks.init" = { path = "/etc/init.d/automation-webhooks" }
"scripts/automation-webhooks.logrotate" = { path = "/etc/logrotate.d/automation-webhooks" }
"scripts/automation-webhooks.monit" = { path = "/etc/monit.d/automation-webhooks.monit" }
```

I think an mdbook or rustdocs would be the best way to comprehensively document the introduced `Cargo.toml` metadata settings. The cargo book's `manifest format` section might be a good source of inspiration for how best to structure such a document file:///home/jlusby/git/rust/cargo/src/doc/book/reference/manifest.html.

If you do write such a document definitely link to it from the README near the more basic example of the most commonly used syntax.

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
