### ISSUE TITLE
``cargo rpm init`` generates malformed TOML

### ISSUE THREAD

**Issue by phi-gamma** [RustRPM/cargo-rpm#39]
In a project with a binary at ``src/bin/foo.rs``, running
``cargo rpm init`` adds these lines to ``Cargo.toml``:

    [package.metadata.rpm]
    buildflags = ["--release"]

    [package.metadata.rpm.targets]
    ./src/bin/foo = { path = "/usr/bin/./src/bin/foo" }

which is not well formed syntax and causes cargo to error out:

    $ cargo build
    error: failed to parse manifest at `/src/rust-dev/playground/cargo-rpm/test-bin/Cargo.toml`
    
    Caused by:
      could not parse input as TOML
    
    Caused by:
      expected a table key, found a period at line 15

I’m using cargo-fmt (0.6.0) on Fedora 30.

**Comment by tarcieri** [comment]
Hrmm, I thought we had the case of `--bin` apps with their `main.rs` located in `src/bin` covered (it's one we actually use quite frequently) but after reviewing the apps we package as RPMs I see the ones we deploy are presently all `src/main.rs`.

So, sorry about that, this is definitely a case we need to support and one which will impact our own apps soon!

**Comment by mikart143** [comment]
How about this fix ? Will we get this ?

**Comment by tarcieri** [comment]
@mikart143 please read this and know your place before commenting https://twitter.com/bascule/status/1227484563024142336?s=21

**Comment by tarcieri** [comment]
We'll get it whenever someone has time to contribute it.

**Comment by ximon18** [comment]
Unless I'm missing something this is an annoyance but easily solved, e.g. in my case I modified the following generated `Cargo.toml` lines and then `cargo rpm build` worked and the produced RPM file installed cleanly in a CentOS-8 Docker container:

Generated by `cargo rpm init`
```
[package.metadata.rpm.targets]
./src/bin/somebinary = { path = "/usr/bin/./src/bin/somebinary" }
./src/bin/someotherbinary = { path = "/usr/bin/./src/bin/someotherbinary" }
```

Fixed by hand:
```
[package.metadata.rpm.targets]
somebinary = { path = "/usr/bin/somebinary" }
someotherbinary = { path = "/usr/bin/someotherbinary" }
```

**Comment by tarcieri** [comment]
Yeah, this seems like a minor bug in terms of how the paths are computed for the `TargetType::MultiBin` case

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
