### ISSUE TITLE
musl

### ISSUE THREAD

**Issue by jamessewell** [RustRPM/cargo-rpm#40]
Hey,

I can see some discussion, but I can't for the life of me get a musl build to work (and be triggered by the `cargo rpm build` command.

Is there a trick to getting `--release --target x86_64-unknown-linux-musl ` passed through when compiling and then getting `cargo-rpm` to get the code form `./target/x86_64-unknown-linux-musl` ?

**Comment by tarcieri** [comment]
I think in general support for alternative targets is lacking, but definitely a useful feature in this particular circumstance

**Comment by jamessewell** [comment]
What was this PR about, it reads like it adds support?

https://github.com/RustRPM/cargo-rpm/pull/24

**Comment by tarcieri** [comment]
Oh right, I guess we had a PR that was supposed to add it 😅 

I never tried that out, but it seems it's not working for you?

**Comment by chewi** [comment]
It does work now but it's a little inflexible as you can only support one target. It would be better if you could pass `--target` as an argument like cargo-deb does. Perhaps it passes all arguments through to the build? I'll happily blame @mthebridge though as I work with him. :wink:

**Comment by tarcieri** [comment]
We can probably support both, overriding the supplied target with a command-line argument if the latter is present.

Also note v0.7.0 is out with the changes from #24 so I'll go ahead and close this issue.
