### ISSUE TITLE
Allow multiple target architectures

### ISSUE THREAD

**Issue by rubdos** [RustRPM/cargo-rpm#47]
I'm building an application that should target multiple target architectures. Currently, specifying the architecture for the RPM is possible in Cargo.toml under `package.metadata.rpm.cargo.target`, which is checked into version control.

`cargo-rpm` should rather take into account what cargo itself would consider the target, which is by passing either `--target` on CLI or reading `~/.cargo/config` and `.cargo/config`.  I am using the latter, e.g.

```toml
[build]
target = "arm-unknown-linux-gnueabihf"
```

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
