### ISSUE TITLE
rpmbuild fails when path is not /usr/bin

### ISSUE THREAD

**Issue by dansondergaard** [RustRPM/cargo-rpm#6]
I changed the path set in `Cargo.toml`:

```
change-password = { path = "/usr/local/bin/change-password" }
```

Running `cargo rpm build --verbose` then gives me this error:

```
[m[32m[1m     Running[m cargo build --release
    Finished release [optimized] target(s) in 0.02s
[m[32m[1m    Creating[m release archive: change-password-0.1.0.tar.gz
[m[32m[1m    Building[m change-password-0.1.0.rpm (using rpmbuild 4.11.3)
[m[32m[1m     Running[m /usr/bin/rpmbuild -D _topdir /home/das/system-tools/change-password/target/release/rpmbuild -D _tmppath /home/das/system-tools/change-password/target/release/rpmbuild/tmp -ba SPECS/change-password.spec
[m[32m[1m    rpmbuild[m Executing(%prep): /bin/sh -e /home/das/system-tools/change-password/target/release/rpmbuild/tmp/rpm-tmp.v6zmQQ
+ umask 022
+ cd /home/das/system-tools/change-password/target/release/rpmbuild/BUILD
+ cd /home/das/system-tools/change-password/target/release/rpmbuild/BUILD
+ rm -rf change-password-0.1.0
+ /usr/bin/gzip -dc /home/das/system-tools/change-password/target/release/rpmbuild/SOURCES/change-password-0.1.0.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd change-password-0.1.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
[m[32m[1m    rpmbuild[m Executing(%install): /bin/sh -e /home/das/system-tools/change-password/target/release/rpmbuild/tmp/rpm-tmp.IKtW4R
+ umask 022
+ cd /home/das/system-tools/change-password/target/release/rpmbuild/BUILD
+ '[' /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64 '!=' / ']'
+ rm -rf /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64
++ dirname /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64
+ mkdir -p /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT
+ mkdir /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64
+ cd change-password-0.1.0
+ rm -rf /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64
+ mkdir -p /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64
+ cp -a usr /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64
[m[32m[1m    rpmbuild[m Processing files: change-password-0.1.0-1.x86_64
error: File not found by glob: /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64/usr/bin/*
    File not found by glob: /home/das/system-tools/change-password/target/release/rpmbuild/BUILDROOT/change-password-0.1.0-1.x86_64/usr/bin/*
[m[32m[1m    rpmbuild[m 
[m[32m[1m    rpmbuild[m 
[m[32m[1m    rpmbuild[m RPM build errors:
[m[31m[1merror:[m error running /usr/bin/rpmbuild (exit status: exit code: 1)
```

Clearly `rpmbuild` seems to assume that the file is located in `/usr/bin/`.

**Comment by tarcieri** [comment]
The only supported directories right now are `/usr/bin` and `/usr/sbin`. That could perhaps be better documented.

**Comment by tarcieri** [comment]
For reference, here's the option to use `sbin`:

https://github.com/RustRPM/cargo-rpm/blob/4b2071a9508b16c74bd549fda162cc92aba5cd4e/src/init.rs#L27

**Comment by dansondergaard** [comment]
Yeah, that's a bit confusing. Is it difficult to support an arbitrary path?

**Comment by tarcieri** [comment]
Right now it uses the `%{_bindir}` and `%{_sbindir}` macros:

https://fedoraproject.org/wiki/Packaging:RPMMacros

**Comment by tylerhawkes** [comment]
I'm running into this on mac where brew installed rpmbuild into /usr/local/bin/rpmbuild and with protections on, I can't symlink it into /usr/bin or /usr/sbin.

**Comment by tarcieri** [comment]
@tylerhawkes that seems like a different issue... this issue is about which directories binaries in resulting `.rpm` packages can be located, not the `cargo-rpm` tool itself

**Comment by vlycop** [comment]
Hello :)
I know it is rude to reply on closed and old issue, but since this is highly referenced on google, i though it would be a good idea to add a solution to this ?
Since i encountered it while building RPM for the first time, i didn't know what to look for and what served what purpose.

Most of the macros are based on `%{_prefix}`, but you can redefine them !
For example, adding `%define _prefix /usr/local` to my spec file in order to fix the issue you had.
Thank to this, include, bin, share, lib, every folder i needed moved from `/usr` to `/usr/local`

But all of this is to build the `%files%` part of the .spec file. If you have specific requirement, you can simply edit `%{_bindir}/*` and write whatever you want. It's also there where you can define extra file if you encounter `Installed (but unpackaged) file(s)` errors

**Comment by tony-iqlusion** [comment]
This issue was closed before it could be properly addressed.

I've gone ahead and reopened it.

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
