### ISSUE TITLE
rpm-rs backend

### ISSUE THREAD

**Issue by tarcieri** [RustRPM/cargo-rpm#60]
`rpm-rs` is a pure Rust library for building and parsing RPMs:

https://github.com/Richterrettich/rpm-rs

It includes support for much of the functionality in (lib)rpmbuild, including producing signed RPMs.

Unfortunately `cargo-rpm` is presently largely driven by `.spec` files, so supporting it would be a pretty major change.

It might be nice to support building RPMs without a spec file by using `rpm-rs` (i.e. via Cargo metadata alone), while retaining the current `rpmbuild`-based backend as well.

**Comment by saidsay-so** [comment]
I started working on this. This is also the reason why I wanted to add the "build hooks".

**Comment by tarcieri** [comment]
@MusiKid aah, interesting. I think it'd be cool if you could make the `rpmbuild` invocation into a "build hook"

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
