### ISSUE TITLE
Support custom directory for spec file location

### ISSUE THREAD

**Issue by anupdhml** [RustRPM/cargo-rpm#72]
Right now, `cargo-rpm` expects the spec file to be at `.rpm` directory in project root. It would be nice to support reads (as well as initial write) of the spec file from a user-defined location in the project.

---

Thinking of an `--output` arg to `cargo rpm init`, to specify the directory where the spec file would be written to (if the arg is not supplied, spec would still be written to current default `.rpm`).

As part of init, the directory would also be included as a new entry in Cargo.toml's `[package.metadata.rpm]`, from which `cargo rpm build` can pick up the spec file. Example layout:

```
[package.metadata.rpm]
config-dir = "packaging/rpm"
```

This would also make it clear from configuration that cargo-rpm relies on the assets in `config-dir`.

If this proposal makes sense, I would be happy to work on a PR to add it. 

Suggestions are welcome!

**Comment by tarcieri** [comment]
Sounds good to me, perhaps:

- `cargo rpm init --output [SPEC FILE]`
- `cargo rpm build --spec [SPEC FILE]`
