### ISSUE TITLE
Cargo workspaces support

### ISSUE THREAD

**Issue by l4l** [RustRPM/cargo-rpm#79]
Currently, if `cargo-rpm` launched from within the workspace root the following error is printed:

```
error: no [package] section in Cargo.toml!
```

As I may guess, the workspaces are not supported and for now it's just possible to iterate over necessary crates manually and for each execute `cargo rpm build`. Would be nice, if it supported from cargo-rpm itself. List of possible subtasks:

- new command `cargo rpm list` that lists projects that has a (valid) .rpm sub-folder at that workspace;
- executing `cargo rpm init` at workspace root inits .rpm for each crate in that workspace, optionally with specified crate list;
- executing `cargo rpm build` at workspace root builds each crate in a workspace (optionally) skipping ones without .rpm sub-folder;
- flag `-p`/`--package` for selecting a package to work with (i.e. `cargo rpm -p mypackage build` works the same as changing directory to `mypackage` package and then launching `cargo rpm build`).

**Comment by tony-iqlusion** [comment]
This sounds like a good plan

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
