### ISSUE TITLE
Help message lacks information

### ISSUE THREAD

**Issue by drahnr** [RustRPM/cargo-rpm#80]
From the `--help` message it is not clear how to properly use `cargo-rpm` - that is a sub-optimal first encounter:

```
$cargo rpm --help
error: unrecognized command `--help`

cargo-rpm 0.8.0
Tony Arcieri <tony@iqlusion.io>
Build RPMs from Rust projects using Cargo workflows

FLAGS:
    -c, --config CONFIG       path to configuration file
    -h, --help                print help message
    -v, --verbose             be verbose
```

which does not list `init` or any subcommand and also exits with exitcode `1` rather than `0`.

**Comment by tony-iqlusion** [comment]
`cargo rpm help` will display the command list.

I agree that `cargo rpm --help` should do the same and the current behavior is a bug.

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
