### ISSUE TITLE
cargo rpm init fails at [target.cfg(linux)'.dependencies]

### ISSUE THREAD

**Issue by emsr** [RustRPM/cargo-rpm#88]
When I run (on Linux)
cargo rpm init
I get an error message:
error: cargo-rpm fatal error: parse error: no variant of enum CargoLicense found in flattened data for key `package` at line 46 column 1

I assume this is referring to this line(46) in my Cargo.toml:
[target.'cfg(linux)'.dependencies]

If I comment this out it bombs on line 43:
[target.'cfg(windows)'.dependencies]

**Comment by tony-iqlusion** [comment]
Do you have a `license` key in your `[package]` section?

**Comment by emsr** [comment]
I do now. I figures that out eventually.

**Comment by emsr** [comment]
Now I get a .rpm and a template.
