### ISSUE TITLE
build subcommand verbose print topdir arg should a quote

### ISSUE THREAD

**Issue by pymongo** [RustRPM/cargo-rpm#93]
current verbose print is

> Running rpmbuild -ba SPECS/a.spec -D _topdir /home/w/repos/temp/a/target/release/rpmbuild -D _tmppath /home/w/repos/temp/a/target/release/rpmbuild/tmp

when I copy this command run again get `error: Macro %_topdir has empty body`

the arg should print to `-D '_topdir /home/w/repos/temp/a/target/release/rpmbuild'` with quote to include whitespace

https://github.com/iqlusioninc/cargo-rpm/blob/ca2f28d012529914c59a1cc93edfd059bf294e21/src/builder.rs#L357

current code use join to concat args can improve?

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
