### ISSUE TITLE
can't switch between release and debug builds

### ISSUE THREAD

**Issue by Licenser** [RustRPM/cargo-rpm#94]
There seems to be no way right now to create both a debug and release build of an RPM without modifying the `Cargo.toml` it would be nice to have a flag like `--profile<debug>` that allows overwriting the metadata.

The reason being is that release builds with rust take **a lot** of time and in CI, to test rpm creation it would often be enough to build as debug which is fairly quick, and see if the archive is usable.

edit:

cargo-deb offers the `--profile` flag to overwrite the profile on the command line

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
