### ISSUE TITLE
error: missing field 'description' for key 'package'

### ISSUE THREAD

**Issue by dmitris** [RustRPM/cargo-rpm#95]
When trying to run `cargo rpm init`, I'm getting the following error:
```
$ cargo rpm init
error: cargo-rpm fatal error: parse error: missing field `description` for key `package` at line 8 column 1
```

How is one supposed to provide the description field? Could we add it to the `README` documentation (or have I missed some doc piece that describes it)? Thanks.

**Comment by tony-iqlusion** [comment]
It's looking for a `description` key in the `[package]` section of Cargo.toml.

This is a standard attribute of `[package]`:

https://doc.rust-lang.org/cargo/reference/manifest.html#the-description-field

**Comment by dmitris** [comment]
thanks @tony-iqlusion!  Would it be worth to add to the README something like:
`to use cargo-rpm, you need to have the `package` and `license` attributes in Cargo.toml.  See <link> for the additional information.` ?

**Comment by tony-iqlusion** [comment]
Sure. Feel free to open a PR.

**Comment by tony-iqlusion** [comment]
`cargo-rpm` is unmaintained: #96
